openapi: 3.0.0
info:
  title: K8S METRICS API
  version: "1.0"
paths:
  /ping:
    get:
      summary: Ping API (returns pong)
      responses:
        "200":
          description: OK
  "/metric":
    get:
      summary: Info about object
      responses:
        "200":
          description: OK
          content:
            text/plain:
              schema:
                type: string
                example: pong
        "400":
          description: BAD_REQUEST
        "404":
          description: NOT_FOUND
        "500":
          description: ERROR
  "/update":
    get:
      summary: Info about object
      responses:
        "200":
          description: OK
        "400":
          description: BAD_REQUEST
        "404":
          description: NOT_FOUND
        "500":
          description: ERROR
servers:
  - url: /api/v1

