---
apiVersion: v1
kind: Service
metadata:
    name: metrics
    namespace: monitoring
    annotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "8888"
      prometheus.io/path: "/api/v1/metric"
spec:
    ports:
    - port: 8888
      protocol: TCP
      targetPort: 8888
      name: http
    selector:
      app: metrics-app
    type: NodePort
---